
SELECT a.STUDENT_ID,a.STUDENT_NAME,a.ACADEMIC_YEAR,a.FATHER_NAME,a.MOTHER_NAME,a.DATE_OF_BIRTH,a.CLASS,SUBJECT,
       a.PERIODIC_TEST_Q1,a.NOTE_BOOK_Q1,a.SUBJECT_ENRICHMENT_Q1,a.Q1_EXAM,a.QUARTER_1_TOTAL,
	   case 
	   when ((a.QUARTER_1_TOTAL/50)*100) between 80 and 100 then 'OUTPERFORM' 
	   when ((a.QUARTER_1_TOTAL/50)*100) between 60 and 79 then 'UNDERPERFORM' 
	   when ((a.QUARTER_1_TOTAL/50)*100) between 33 and 59 then 'AVERAGE' 
	   else 'Fail' 
	   end AS QUARTER_1_PERFORMANCE,
	   a.PERIODIC_TEST_Q2,a.NOTE_BOOK_Q2,a.SUBJECT_ENRICHMENT_Q2,a.HALF_YEARLY,a.HALF_YEARLY_TOTAL,
	   case 
	   when a.HALF_YEARLY_TOTAL between 80 and 100 then 'OUTPERFORM' 
	   when a.HALF_YEARLY_TOTAL between 60 and 79 then 'UNDERPERFORM' 
	   when a.HALF_YEARLY_TOTAL between 33 and 59 then 'AVERAGE' 
	   else 'Fail' 
	   end AS HALF_YEARLY_PERFORMANCE,
	   a.PERIODIC_TEST_Q3,a.NOTE_BOOK_Q3,a.SUBJECT_ENRICHMENT_Q3,a.Q3_EXAM,a.QUARTER_3_TOTAL,
	   case 
	   when ((a.QUARTER_3_TOTAL/50)*100) between 80 and 100 then 'OUTPERFORM' 
	   when ((a.QUARTER_3_TOTAL/50)*100) between 60 and 79 then 'UNDERPERFORM' 
	   when ((a.QUARTER_3_TOTAL/50)*100) between 33 and 59 then 'AVERAGE' 
	   else 'Fail' 
	   end AS QUARTER_3_PERFORMANCE,
	   a.PERIODIC_TEST_Q4,a.NOTE_BOOK_Q4,a.SUBJECT_ENRICHMENT_Q4,a.ANNUAL_Q4,a.ANNUAL_TOTAL,
	   case 
	   when a.ANNUAL_TOTAL between 80 and 100 then 'OUTPERFORM' 
	   when a.ANNUAL_TOTAL between 60 and 79 then 'UNDERPERFORM' 
	   when a.ANNUAL_TOTAL between 33 and 59 then 'AVERAGE' 
	   else 'Fail' 
	   end AS ANNUAL_PERFORMANCE,
	   round(((a.QUARTER_1_TOTAL+a.HALF_YEARLY_TOTAL+a.QUARTER_3_TOTAL+a.ANNUAL_TOTAL)/3),2) as GRAND_TOTAL,
	   CASE 
        WHEN ((a.QUARTER_1_TOTAL+a.HALF_YEARLY_TOTAL+a.QUARTER_3_TOTAL+a.ANNUAL_TOTAL)/3) BETWEEN 91 AND 100 THEN 'A1'
        WHEN ((a.QUARTER_1_TOTAL+a.HALF_YEARLY_TOTAL+a.QUARTER_3_TOTAL+a.ANNUAL_TOTAL)/3) BETWEEN 81 AND 90 THEN 'A2'
        WHEN ((a.QUARTER_1_TOTAL+a.HALF_YEARLY_TOTAL+a.QUARTER_3_TOTAL+a.ANNUAL_TOTAL)/3) BETWEEN 71 AND 80 THEN 'B1'
        WHEN ((a.QUARTER_1_TOTAL+a.HALF_YEARLY_TOTAL+a.QUARTER_3_TOTAL+a.ANNUAL_TOTAL)/3) BETWEEN 61 AND 70 THEN 'B2'
        WHEN ((a.QUARTER_1_TOTAL+a.HALF_YEARLY_TOTAL+a.QUARTER_3_TOTAL+a.ANNUAL_TOTAL)/3) BETWEEN 51 AND 60 THEN 'C1'
        WHEN ((a.QUARTER_1_TOTAL+a.HALF_YEARLY_TOTAL+a.QUARTER_3_TOTAL+a.ANNUAL_TOTAL)/3) BETWEEN 41 AND 50 THEN 'C2'
        WHEN ((a.QUARTER_1_TOTAL+a.HALF_YEARLY_TOTAL+a.QUARTER_3_TOTAL+a.ANNUAL_TOTAL)/3) BETWEEN 33 AND 40 THEN 'D'
        ELSE 'E'
	   END AS GRADE
FROM (
SELECT sp.STUDENT_ID,CONCAT(sp.FIRST_NAME,' ',sp.MIDDLE_NAME,' ',sp.LAST_NAME) as STUDENT_NAME,sp.ACADEMIC_YEAR,pp.FATHER_NAME,pp.MOTHER_NAME,sp.DATE_OF_BIRTH, ci.CLASS_ID as CLASS,
		s.SUBJECT,
	   PERIODIC_TEST_Q1,NOTE_BOOK_Q1,SUBJECT_ENRICHMENT_Q1,Q1_EXAM,
	   COALESCE(PERIODIC_TEST_Q1, 0) + COALESCE(NOTE_BOOK_Q1, 0) + COALESCE(SUBJECT_ENRICHMENT_Q1, 0) + COALESCE(Q1_EXAM, 0) AS QUARTER_1_TOTAL,
	   PERIODIC_TEST_Q2,NOTE_BOOK_Q2,SUBJECT_ENRICHMENT_Q2,HALF_YEARLY,
	   COALESCE(PERIODIC_TEST_Q2, 0) + COALESCE(NOTE_BOOK_Q2, 0) + COALESCE(SUBJECT_ENRICHMENT_Q2, 0) + COALESCE(HALF_YEARLY, 0) AS HALF_YEARLY_TOTAL,
	   PERIODIC_TEST_Q3,NOTE_BOOK_Q3,SUBJECT_ENRICHMENT_Q3,Q3_EXAM,
	   COALESCE(PERIODIC_TEST_Q3, 0) + COALESCE(NOTE_BOOK_Q3, 0) + COALESCE(SUBJECT_ENRICHMENT_Q3, 0) + COALESCE(Q3_EXAM, 0) AS QUARTER_3_TOTAL,
       PERIODIC_TEST_Q4,NOTE_BOOK_Q4,SUBJECT_ENRICHMENT_Q4,ANNUAL_Q4,
	   COALESCE(PERIODIC_TEST_Q4, 0) + COALESCE(NOTE_BOOK_Q4, 0) + COALESCE(SUBJECT_ENRICHMENT_Q4, 0) + COALESCE(ANNUAL_Q4, 0) AS ANNUAL_TOTAL
from STUDENT_PROFILE sp,PARENT_PROFILE pp,CLASS_DETAIL cd,CLASS_INFO ci,SUBJECT s,MARKS m 
WHERE sp.STUDENT_ID = cd.STUDENT_ID 
and sp.STUDENT_ID = pp.STUDENT_ID 
AND cd.CLASS_ID = ci.CLASS_ID  
AND ci.CLASS_NUMBER = s.CLASS_NUMBER 
AND sp.STUDENT_ID = m.STUDENT_ID 
 AND s.SUBJECT = m.SUBJECT 
-- and sp.STUDENT_ID = 'SID-01001'
)a
order by STUDENT_ID asc